AWSTemplateFormatVersion: 2010-09-09
Description: Lambda Alarms

Parameters:
  LambdaFunctionName:
    Type: String
    Default: gbq-lnhstry
  SNSTopicName:
    Type: String
    Default: alarms
  AppLogGroupName:
    Type: String
    Default: gbq-myService-throttle-alarm

Resources:
  LambdaThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Throttle Alarm for myService
      AlarmName: !Sub AWS_fn~${AppLogGroupName}~errors
      AlarmActions: 
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${SNSTopicName}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Threshold: 1
      DatapointsToAlarm: 1
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      Period: 300
      TreatMissingData: missing
  
  LambdaThrottleAlarm:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: /aws/lambda/myService
      FilterPattern: '[ip, id, user, timestamp, request="GET *&download=Yes*", status_code, size]'
      MetricTransformations:
        - MetricValue: 1
          MetricNamespace: GP/GBQ
          DefaultValue: 0
          MetricName: helloThisismymetric
    
