AWSTemplateFormatVersion: 2010-09-09
Description: Lambda Alarms

Resources:
  LambdaThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Throttle Alarm for myService
      AlarmName: gbq-myService-throttle-alarm
      AlarmActions: 
        - arn:aws:sns:us-east-1:035458612173:alarms
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Threshold: 1
      DatapointsToAlarm: 1
      Dimensions:
        - Name: FunctionName
          Value: myService
      Period: 300
      TreatMissingData: missing
